# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend
    spec:
      containers:
        - name: backend
          image: europe-southwest1-docker.pkg.dev/isekai-comics/isekai-comics/strapi:latest
          ports:
            - containerPort: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: LoadBalancer
